config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Defines the root path route ("/")
  # root "articles#index"
  resources :stores do
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/store.rb
class Store < ApplicationRecord
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/stores_controller.rb
class StoresController < ApplicationController

  def index
    @stores = Store.all.order(id: :asc)
  end

  def show
    set_store
  end

  def new
    @store = Store.new
  end

  def create
    @store = Store.new store_params
    respond_to do |format|
      if @store.save
        @store = Store.last
        format.html { redirect_to store_path(@store.id), notice: "Store Created", remote: false }
      else
        format.html { render :new }
      end
    end
  end

  def edit
    set_store
  end

  def update
    if set_store.update(store_params)
      redirect_to store_path, notice: "Store Update"
    else
      render :edit, status: :unprocessable_entity
    end
  end

  def destroy
    set_store
    if set_store.destroy
      redirect_to stores_path, alert: "Store deleted"
    else
      redirect_to store_path, alert: "Store not deleted"
    end
  end

  private

  def set_store
    @store = Store.find params[:id]
  end

  def store_params
    params.require(:store).permit!
  end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/stores_helper.rb
module StoresHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>TestingCrud</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Roboto:wght@400;900&display=swap" rel="stylesheet">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap-icons@1.10.3/font/bootstrap-icons.css">
    
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <div class="col-3"><%= render '/shared/flash' %></div>
    <%= yield %>
  </body>
</html>

app/views/shared/_flash.html.erb
<h3 class="bg-success"><%= notice %></h3>
<h3 class="bg-danger"><%= alert %></h3>

app/views/stores/_form.html.erb
<div class="modal-contet">
  <div class="modal-header">
    <h3 class="modal-title">Article form</h3>
  </div>
  <div class="modal-body">
    <%= form_with model: @store do |f| -%>
      <div class="alert alert-danger" style="display: none" id="record-errors"></div>
      <div class="row">
        <div class="row">
          <div class="col-sm-6">
            <td><%= f.label :article -%> *</td>
            <td><%= f.text_field :article, required: true, class: 'form-control' -%></td>
          </div>
          <div class="col-sm-6">
            <td></td>
            <td></td>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6">
            <td><%= f.label :state -%> *</td>
            <td><%= f.text_field :state, required: true, class: 'form-control' -%></td>
          </div>
          <div class="col-sm-6">
            <td><%= f.label :price -%> *</td>
            <td><%= f.text_field :price, required: true, class: 'form-control' -%></td>
          </div>
        </div>
        <div class="row">
          <div class="col-sm-6">
            <td><%= f.label :in_warehouse -%> *</td>
            <td><%= f.text_field :in_warehouse, required: true, class: 'form-control' -%></td>
          </div>
          <div class="col-sm-6">
            <td><%= f.label :on_counter -%> *</td>
            <td><%= f.text_field :on_counter, required: true, class: 'form-control' -%></td>
          </div>
        </div>
      </div>
      <div class="modal-footer p-3">
        <div class="container text-end">
          <%= link_to "Close", stores_path, class: 'btn btn-secondary' %>
          <button type="submit" class="btn btn-primary">Save changes</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

app/views/stores/edit.html.erb
<div class="container">
  <div class="content-header">
    <div class="header-section">
      <h1><small>Edit article to the store</small></h1>
    </div>
  </div>
  <ul class="breadcrumb breadcrumb-top">
  <li><a href="<%= stores_path %>">Home</a></li>
  </ul>
  <section>
    <%= render 'form' %>
  </section>
</div>

app/views/stores/index.html.erb
<div class="container">
  <div class="content-header">
    <div class="header-section">
      <h1><small>Access the information of the store</small></h1>
      <%= link_to "Add Article", new_store_path(@store), class: 'btn btn-success' %>
    </div>
  </div>
  <div class="block full block-alt-noborder table-responsive form-control mt-3">
    <table class="table data-table">
      <thead>
        <tr>
          <th>Id</th>
          <th>Article</th>
          <th>State</th>
          <th>Price</th>
        </tr>
      </thead>
      <tbody>
        <% @stores.each do |store| %>
          <tr>
            <td><%= store.id %></td>
            <td><a href="<%= store_path(store.id) %>" ><%= store.article %></a></td>
            <td><%= store.state %></td>
            <td><%= store.price %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</div>

app/views/stores/new.html.erb
<div class="container">
  <div class="content-header">
    <div class="header-section">
      <h1><small>Add article to the store</small></h1>
    </div>
  </div>
  <ul class="breadcrumb breadcrumb-top">
  <li><a href="<%= stores_path %>">Home</a></li>
  </ul>
  <section>
    <%= render 'form' %>
  </section>
</div>

app/views/stores/show.html.erb
<div class="container">
  <div class="content-header">
    <div class="header-section">
      <h1><small>Check this article details</small></h1>
      <%= link_to "Edit", edit_store_path(@store.id), class: 'btn btn-info' %>
    </div>
  </div>
  <ul class="breadcrumb breadcrumb-top">
    <li><a href="<%= stores_path %>">Home</a></li>
  </ul>
  <div class="tab-content">
    <div class="row">
      <br>
      <div class="col-md-4"></div>
        <div class="row form-control">
          <div class="block">
            <table class="table">
              <tr>
                <th>Article: </th>
                <td><%= @store.article -%></td>
              </tr>
              <tr>
                <th>State:</th>
                <td><%= @store.state -%></td>
              </tr>
              <tr>
                <th>Price:</th>
                <td><%= @store.price -%></td>
              </tr>
              <tr>
                <th>In Warehouse:</th>
                <td><%= @store.in_warehouse -%></td>
              </tr>
              <tr>
                <th>On Counter:</th>
                <td><%= @store.on_counter -%></td>
              </tr>
              <tr>
                <th>Create at:</th>
                <td><%= @store.created_at -%></td>
              </tr>
              <tr>
                <th>Update at:</th>
                <td><%= @store.updated_at -%></td>
              </tr>
              <tr>
                <td></td>
                <td colspan="2"><%= link_to "Delete", store_path(@store), class: 'btn btn-danger', data: { 
                  turbo_method: :delete,
                  turbo_confirm: 'Are you sure to DELETE this article?'
                  } %></td>
              </tr>
            </table>
          </div>
        </div>
      </div>
		</div>
  </div>
</div>